### ISSUE TITLE
違うページに遷移しても検索結果は残るようにする

### ISSUE THREAD

**Issue by tsutarou10** [tsutarou10/silver-rack-sandbox#18]
https://medium.com/coding-with-flutter/flutter-case-study-multiple-navigators-with-bottomnavigationbar-90eb6caa6dbf

**Comment by Kosaku-y** [comment]
https://speakerdeck.com/txmn/flutterfalse-bottom-navigation-niyoruhua-mian-qian-yi-nituite?slide=11
